import { UserData, getWeekNumber } from './scoring';

export function generateMockData(): UserData[] {
  const currentWeek = getWeekNumber(new Date());
  
  return [
    {
      id: '1',
      username: '@crypto_alex',
      displayName: 'Alex Thompson',
      followers: 15000,
      avatar: 'https://images.pexels.com/photos/2379004/pexels-photo-2379004.jpeg?auto=compress&cs=tinysrgb&w=150&h=150&dpr=2',
      lastWeekActive: true,
      tweets: [
        {
          id: '1a',
          content: 'Just launched our new DeFi protocol! 🚀 #crypto #defi',
          likes: 234,
          retweets: 45,
          timestamp: new Date(2025, 0, 13, 10, 30),
          weekNumber: currentWeek,
          orderInWeek: 1,
        },
        {
          id: '1b',
          content: 'Market analysis: Bitcoin showing strong support at $42k 📈',
          likes: 156,
          retweets: 28,
          timestamp: new Date(2025, 0, 14, 15, 45),
          weekNumber: currentWeek,
          orderInWeek: 2,
        },
        {
          id: '1c',
          content: 'Reminder: Always DYOR before investing! Safety first 🛡️',
          likes: 89,
          retweets: 12,
          timestamp: new Date(2025, 0, 15, 9, 15),
          weekNumber: currentWeek,
          orderInWeek: 3,
        },
      ],
    },
    {
      id: '2',
      username: '@sarah_tech',
      displayName: 'Sarah Chen',
      followers: 8500,
      avatar: 'https://images.pexels.com/photos/1239291/pexels-photo-1239291.jpeg?auto=compress&cs=tinysrgb&w=150&h=150&dpr=2',
      lastWeekActive: false,
      tweets: [
        {
          id: '2a',
          content: 'AI is revolutionizing healthcare - exciting times ahead! 🏥🤖',
          likes: 189,
          retweets: 67,
          timestamp: new Date(2025, 0, 13, 14, 20),
          weekNumber: currentWeek,
          orderInWeek: 1,
        },
        {
          id: '2b',
          content: 'Just finished reading "Superintelligence" - mind blown 🧠',
          likes: 95,
          retweets: 23,
          timestamp: new Date(2025, 0, 16, 11, 30),
          weekNumber: currentWeek,
          orderInWeek: 2,
        },
      ],
    },
    {
      id: '3',
      username: '@dev_mike',
      displayName: 'Mike Rodriguez',
      followers: 22000,
      avatar: 'https://images.pexels.com/photos/1222271/pexels-photo-1222271.jpeg?auto=compress&cs=tinysrgb&w=150&h=150&dpr=2',
      lastWeekActive: true,
      tweets: [
        {
          id: '3a',
          content: 'New React 19 features are game-changing! 🔥 Thread 🧵',
          likes: 445,
          retweets: 128,
          timestamp: new Date(2025, 0, 12, 16, 45),
          weekNumber: currentWeek,
          orderInWeek: 1,
        },
      ],
    },
    {
      id: '4',
      username: '@marketing_jen',
      displayName: 'Jennifer Liu',
      followers: 12500,
      avatar: 'https://images.pexels.com/photos/1181519/pexels-photo-1181519.jpeg?auto=compress&cs=tinysrgb&w=150&h=150&dpr=2',
      lastWeekActive: true,
      tweets: [
        {
          id: '4a',
          content: 'Content marketing in 2025: Authenticity beats algorithms 📱',
          likes: 278,
          retweets: 89,
          timestamp: new Date(2025, 0, 14, 13, 15),
          weekNumber: currentWeek,
          orderInWeek: 1,
        },
        {
          id: '4b',
          content: 'Personal branding tip: Show your journey, not just results ✨',
          likes: 156,
          retweets: 34,
          timestamp: new Date(2025, 0, 15, 18, 30),
          weekNumber: currentWeek,
          orderInWeek: 2,
        },
      ],
    },
    {
      id: '5',
      username: '@startup_dan',
      displayName: 'Dan Peterson',
      followers: 6800,
      avatar: 'https://images.pexels.com/photos/2182970/pexels-photo-2182970.jpeg?auto=compress&cs=tinysrgb&w=150&h=150&dpr=2',
      lastWeekActive: false,
      tweets: [
        {
          id: '5a',
          content: 'Bootstrapped to $100k ARR in 8 months! Here\'s what I learned 📊',
          likes: 523,
          retweets: 156,
          timestamp: new Date(2025, 0, 13, 12, 0),
          weekNumber: currentWeek,
          orderInWeek: 1,
        },
        {
          id: '5b',
          content: 'Founder tip: Customer feedback > feature requests 💡',
          likes: 67,
          retweets: 18,
          timestamp: new Date(2025, 0, 16, 10, 45),
          weekNumber: currentWeek,
          orderInWeek: 2,
        },
        {
          id: '5c',
          content: 'Building in public creates accountability and community 🏗️',
          likes: 134,
          retweets: 29,
          timestamp: new Date(2025, 0, 17, 14, 20),
          weekNumber: currentWeek,
          orderInWeek: 3,
        },
      ],
    },
  ];
}